### ISSUE TITLE
Order roles alphabetically in the role list provided by the !roles commands

### ISSUE THREAD

**Issue by alexandrutodea** [AEnterprise/GearBot#14]
The `!roles` command displays a list that is not ordered alphabetically making it really hard to navigate through if the server has a big number of roles. Ordering the list alphabetically would make navigating through it a lot easier, especially in my server which has a role for each language that was a part of Discord's crowdin translations project among other staff roles

![image](https://user-images.githubusercontent.com/20445412/43734323-042edab8-99c0-11e8-99ae-b9fc81c8c7a3.png)

**Comment by AEnterprise** [comment]
i'll combine this with just cleaning this up in general, it works pretty well on desktop but is a disaster on mobile
