### ISSUE TITLE
You can warn yourself if you are the owner [bug]

### ISSUE THREAD

**Issue by Kitty-Therapist** [AEnterprise/GearBot#144]
If you have GearBot in the server, and you are the owner. You are able to add an warning to yourself.

**Steps to Reproduce:**
- Add GearBot to the server you own.
- Do !warn <your userID or mention yourself> <reason>
- Observes of what GearBot does.
**Expected Result:** 
GearBot should deny, and state that you cannot warn yourself.
**Actual Result:**
GearBot adds an warning to you, giving yourself an infraction. 
**Screenshot:**
![image](https://user-images.githubusercontent.com/31807465/51295593-532ad800-19e6-11e9-909c-0ec698c11e38.png)

**Comment by Superie** [comment]
![discordcanary_khcbekw13w](https://user-images.githubusercontent.com/40526207/51295831-2399c100-1a22-11e9-9e83-9a50a97b7345.png)
