### ISSUE TITLE
make warn to work for people who leaves the server

### ISSUE THREAD

**Issue by Kitty-Therapist** [AEnterprise/GearBot#148]
Sometimes people will do something that requires an moderation actions, but know that they will get in trouble by doing on so. So they leave in order to avoid the punishment, but sometimes the infractions are too minor to even ban them so it'd be two infractions to ban, and then unban. 

By making the warn to work for people who leaves the server, it would save us time and amount of infractions for users who may leave the server in case they come back in the future references (if they're left without any moderation actions) and keep on doing it again and again.

**Comment by AEnterprise** [comment]
on second though i won't be allowing this, the risk for abuse is a bit too high for people just adding joke infractions to people who are not even in the server

i do plan on allowing adding notes to people who are not in the server, so the same can be achieved that way
