### ISSUE TITLE
Changing the channel's name causes the bot to think that the topic changed as well

### ISSUE THREAD

**Issue by CanTheCoderBoi** [AEnterprise/GearBot#174]
![resim](https://user-images.githubusercontent.com/32599057/53305010-1b3c6d80-388d-11e9-9a56-66db26819b2c.png)

I will try to reproduce this in different ways as well.

**Comment by CanTheCoderBoi** [comment]
Seems like it's not a one time thing. (Informing)
![resim](https://user-images.githubusercontent.com/32599057/53305076-0ca28600-388e-11e9-9abe-96f419dee573.png)

**Comment by AEnterprise** [comment]
need to handle the inconsitent api, shouldn't be too hard
