### ISSUE TITLE
if update doesn't clear the cache

### ISSUE THREAD

**Issue by Kitty-Therapist** [AEnterprise/GearBot#183]
**Steps to Reproduce:**

- Give an infraction to a random person.
- Run !inf search
- Grab the reason ID, for example, mine could be 1337.
- Run the following command ``!inf update 1337 | This is a professional test.``
- Note how GearBot confirms that it has updated.
- Run !inf search again and observe.

**Expected Result:** The infraction should be updated with the new reason.
**Actual Result:** The infraction is not updated, as if GearBot completely ignored it other than giving the confirmation.

**Comment by AEnterprise** [comment]
if it gave the confirmation then the reason updated, though i guess the caching could be misbehaving, did you try running the search again after a few minutes?

**Comment by AEnterprise** [comment]
confirmed to be caching issue

**Comment by AEnterprise** [comment]
fixed
