### ISSUE TITLE
(Possibly) incorrect command in docs?

### ISSUE THREAD

**Issue by pnfcre** [AEnterprise/GearBot#189]
Hi there,

I recently noticed that the ["How do I use selfroles?"](https://gearbot.rocks/docs/guides/selfroles) section in GearBot's docs maybe has incorrect information. Alternatively, the `!role` command is not working as intended.

![](https://i.imgur.com/7Ve0vPL.png)

But running the `!role` command results in this:

![](https://i.imgur.com/o4RaLy1.png)

I'm not sure if the docs are outdated, and needs to be edited, or if something isn't working properly with the bot — therefore, I submitted this issue.

Thanks!

**Comment by AEnterprise** [comment]
this has been fixed a while back but forgot to close this
