### ISSUE TITLE
Updating a infraction or changing infraction page breaks the infraction embed

### ISSUE THREAD

**Issue by FalseData** [AEnterprise/GearBot#192]
![Screenshot_2019-04-02_21-26-50](https://user-images.githubusercontent.com/46457601/55446541-0c349380-558e-11e9-8822-020bca667ac2.png)

**Comment by adityaxdiwakar** [comment]
I've been able to reproduce this myself in various servers (including the one @FalseData is in).

Quite annoying.

**Comment by FalseData** [comment]
Update on this issue, it only happens when using [tags]

**Comment by adityaxdiwakar** [comment]
Still occurs as of April 4th; 4pm EST.

Reproduction steps (method 1):
1. Pull up a mod's infractory logs
2. Press the right arrow to see page 2, once you do that, the (1/x) changes to (1/1) as if it couldn't load the second page.

Reproduction steps (method 2)
1. Pull up a mod's infractory logs
2. Update one of the infractions on that page
3. The content on the output from step 1 is cleared, showing nothing.

![method1](https://user-images.githubusercontent.com/26584786/55654529-a891ac80-57bf-11e9-86ac-1ec66e024810.gif)

![method2](https://user-images.githubusercontent.com/26584786/55654565-c232f400-57bf-11e9-819c-09807ba74858.gif)
