### ISSUE TITLE
[BUG] GearBot does not seem to detect username changes 

### ISSUE THREAD

**Issue by Kitty-Therapist** [AEnterprise/GearBot#201]
I noticed that there haven’t been any username changes in the mod logs ever since the latest update. 

Coming back to the original GearBot and changing my username, I noted that it wasn’t just GearBoat that was experiencing the issues. GearBot was. 

Steps to Reproduce: 
- Have mod logs set up and ready to go. 
- Change your username to something. 
- Check the logs. 

Expected Result: It should tell that you changed your username. 
Actual Result: It doesn’t say anything, and there is no error.

**Comment by Tarek1337** [comment]
It's because d.py stopped sending username/avatar/discriminator changes to on_member_update, and is now separated into a new event. Which is on_user_update. Which returns a user object. with a before & after parameter.

**Comment by Kitty-Therapist** [comment]
This has been resolved, so closing. :)
