### ISSUE TITLE
New permission lvl: specific people only

### ISSUE THREAD

**Issue by AEnterprise** [AEnterprise/GearBot#23]
This would be permission lvl 4 (currently owner only)
Will need a new command override dict where a whitelist of people can be stored per command of people to grant perm lvl 4 for this command

currently lvl 4 and 5 will become 5 and 6, needs automatic config conversions to not screw up current configrations

**Comment by Mippy** [comment]
Will specific people, AND a trusted role (for example) be a setting?

**Comment by AEnterprise** [comment]
yes, as mentioned above trusted would be a new one that is above admin, the idea is that you can have a server with like entry verification, or not have the bot public, so coinflip and such can be locked down to only vetted members, but not give them mod powers

specific people would be more for people who want to lock some commands to specific people, this would be per command, so giving a single person access to the configure command, or other commands (like announce or such later), that you may not want moderators able to use
