### ISSUE TITLE
investigate webserver capabilities

### ISSUE THREAD

**Issue by AEnterprise** [AEnterprise/GearBot#89]
having gearbot serve web requests himself, maybe for archives, some basic info, the docs, ....

**Comment by AEnterprise** [comment]
i can separate it into 2 separate processes, and implement some limits, linking into fail2ban to get rid of them

**Comment by BlackHoleFox** [comment]
Funny how this worked out, surprisingly well too. :eyes:

**Comment by AEnterprise** [comment]
yup!
